package myprojects.chessproject.virtualchess.frame;


import myprojects.chessproject.virtualchess.geometry.Point;
import java.awt.Dimension;
import java.awt.Toolkit;


public class ChessProjectFrame extends javax.swing.JFrame {


    private boolean colorWhite = true;
    /**
     * Creates new form ChessProjectFrame
     */
    public ChessProjectFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        drawPanel = new DrawPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_Exit = new javax.swing.JMenuItem();
        jMenu_Peaces = new javax.swing.JMenu();
        jMenuItem_TakeOut = new javax.swing.JMenuItem();
        jMenuItem_InitPosition = new javax.swing.JMenuItem();
        jMenuItem_Color = new javax.swing.JMenuItem();
        jMenu_Chess = new javax.swing.JMenu();
        jMenuItem_BordSize = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drawPanel.setBackground(new java.awt.Color(255, 255, 255));
        drawPanel.setForeground(new java.awt.Color(255, 255, 255));
        drawPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                drawPanelMouseReleased(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drawPanelMousePressed(evt);
            }
        });
        drawPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drawPanelMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
                drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 521, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
                drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 414, Short.MAX_VALUE)
        );

        jMenu_File.setText("File");

        jMenuItem_Exit.setText("Exit");
        jMenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ExitActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_Exit);

        jMenuBar1.add(jMenu_File);

        jMenu_Peaces.setText("Peaces");

        jMenuItem_TakeOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, 0));
        jMenuItem_TakeOut.setText("Take out all");
        jMenuItem_TakeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TakeOutActionPerformed(evt);
            }
        });
        jMenu_Peaces.add(jMenuItem_TakeOut);

        jMenuItem_InitPosition.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, 0));
        jMenuItem_InitPosition.setText("Init position");
        jMenuItem_InitPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_InitPositionActionPerformed(evt);
            }
        });
        jMenu_Peaces.add(jMenuItem_InitPosition);

        jMenuItem_Color.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItem_Color.setText("Black");
        jMenuItem_Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ColorActionPerformed(evt);
            }
        });
        jMenu_Peaces.add(jMenuItem_Color);

        jMenuBar1.add(jMenu_Peaces);

        jMenu_Chess.setText("Chess");

        jMenuItem_BordSize.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        jMenuItem_BordSize.setText("Size of the board");
        jMenuItem_BordSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_BordSizeActionPerformed(evt);
            }
        });
        jMenu_Chess.add(jMenuItem_BordSize);

        jMenuBar1.add(jMenu_Chess);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jMenuItem_InitPositionActionPerformed(java.awt.event.ActionEvent evt) {
        ProcessingFrame.init();
        drawPanel.repaint();
    }

    private void jMenuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void jMenuItem_TakeOutActionPerformed(java.awt.event.ActionEvent evt) {
        ProcessingFrame.takeOut();
        drawPanel.repaint();
    }

    private void drawPanelMousePressed(java.awt.event.MouseEvent evt) {
        int x = evt.getX();
        int y = evt.getY();
        ProcessingFrame.choosePeace(new Point(x, y));
    }

    private void drawPanelMouseDragged(java.awt.event.MouseEvent evt) {
        int x = evt.getX();
        int y = evt.getY();
        ProcessingFrame.movePeace(new Point(x, y));
        drawPanel.repaint();
    }

    private void drawPanelMouseReleased(java.awt.event.MouseEvent evt) {
        ProcessingFrame.putPeace();
    }

    private void jMenuItem_ColorActionPerformed(java.awt.event.ActionEvent evt) {
        if (colorWhite) {
            jMenuItem_Color.setText("White");
        }
        else {
            jMenuItem_Color.setText("Black");
        }
        ProcessingFrame.changeColor();
        drawPanel.repaint();
        this.colorWhite = !this.colorWhite;
    }

    private void jMenuItem_BordSizeActionPerformed(java.awt.event.ActionEvent evt) {
        ProcessingFrame.setSizeOfBoard();
        drawPanel.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChessProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChessProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChessProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChessProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                Toolkit kit = Toolkit.getDefaultToolkit();
                Dimension size = kit.getScreenSize();
                int maxX = size.width;
                int maxY = size.height;
                ProcessingFrame.create();

                javax.swing.JFrame main =  new ChessProjectFrame();
                main.setBounds(0, 0, maxX, maxY);
                main.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JPanel drawPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_BordSize;
    private javax.swing.JMenuItem jMenuItem_Color;
    private javax.swing.JMenuItem jMenuItem_Exit;
    private javax.swing.JMenuItem jMenuItem_InitPosition;
    private javax.swing.JMenuItem jMenuItem_TakeOut;
    private javax.swing.JMenu jMenu_Chess;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JMenu jMenu_Peaces;
    // End of variables declaration
}